import { DashboardData } from "./types";

export const initialDashboardData: DashboardData = {
  summary: {
    company_name: "Örnek İşletme",
    target_domain: "ornekfirma.com",
    target_keyword: "kurumsal hizmetler",
    location: "İstanbul",
    current_rank: 18,
    target_rank: 3,
    gbp_score: 58,
    total_actions: 5,
    completed_actions: 1,
    phone: "+90 212 555 0100",
    address: "Merkez Mah. İş Kuleleri Kat:4, Şişli / İstanbul",
    has_whatsapp: true,
    has_quote_form: true,
    has_file_upload: true,
    logo_url: "",
    serp_page_label: "Google 2. Sayfa (8. Sıra)",
  },
  competitors: [
    {
      domain: "ornekfirma.com (Sizin İşletmeniz)",
      title: "Örnek İşletme - Kurumsal Hizmetler ve Çözümler",
      rank_position: 18,
      is_target: true,
      gbp_rating: 4.1,
      gbp_review_count: 12,
      speed_mobile_score: 42,
      speed_desktop_score: 65,
      has_schema: false,
      schema_types: [],
      word_count: 520,
      domain_authority: 28,
      domain_age_years: 6,
      indexed_pages: 35,
      reviews: [
        {
          author: "Murat Kaya",
          rating: 4,
          date: "1 ay önce",
          text: "Hizmetten genel olarak memnun kaldık, iletişim hızlıydı.",
        },
        {
          author: "Selin Yılmaz",
          rating: 5,
          date: "3 ay önce",
          text: "Profesyonel yaklaşım ve zamanında teslimat için teşekkürler.",
        },
      ],
    },
    {
      domain: "liderfirma.com.tr",
      title: "Lider Firma - Profesyonel Kurumsal Hizmetler",
      rank_position: 1,
      is_target: false,
      gbp_rating: 4.9,
      gbp_review_count: 156,
      speed_mobile_score: 85,
      speed_desktop_score: 95,
      has_schema: true,
      schema_types: ["LocalBusiness", "Organization"],
      word_count: 1650,
      domain_authority: 64,
      domain_age_years: 12,
      indexed_pages: 480,
      reviews: [
        {
          author: "Hakan Özdemir",
          rating: 5,
          date: "2 hafta önce",
          text: "Sektörün en güvenilir ekibi. Süreç boyunca her detayla ilgilendiler.",
        },
        {
          author: "Ayşe Çetin",
          rating: 5,
          date: "1 ay önce",
          text: "Harika müşteri deneyimi ve hızlı geri dönüş. Kesinlikle tavsiye ederim.",
        },
      ],
    },
    {
      domain: "uzmancozum.com",
      title: "Uzman Çözüm - Hizmet ve Danışmanlık",
      rank_position: 2,
      is_target: false,
      gbp_rating: 4.8,
      gbp_review_count: 98,
      speed_mobile_score: 78,
      speed_desktop_score: 89,
      has_schema: true,
      schema_types: ["LocalBusiness"],
      word_count: 1340,
      domain_authority: 52,
      domain_age_years: 9,
      indexed_pages: 290,
      reviews: [
        {
          author: "Burak Demir",
          rating: 5,
          date: "3 hafta önce",
          text: "Kaliteli işçilik ve şeffaf fiyatlandırma politikası.",
        },
        {
          author: "Emre Koç",
          rating: 4,
          date: "2 ay önce",
          text: "Teslimat tam vaktinde gerçekleşti, ekip oldukça ilgili.",
        },
      ],
    },
    {
      domain: "prestijhizmet.com",
      title: "Prestij Hizmet - İstanbul",
      rank_position: 3,
      is_target: false,
      gbp_rating: 4.7,
      gbp_review_count: 74,
      speed_mobile_score: 72,
      speed_desktop_score: 84,
      has_schema: true,
      schema_types: ["LocalBusiness", "Service"],
      word_count: 1190,
      domain_authority: 45,
      domain_age_years: 7,
      indexed_pages: 195,
      reviews: [
        {
          author: "Deniz Arslan",
          rating: 5,
          date: "1 ay önce",
          text: "Son derece memnun kaldık, ilgi ve alakaları için teşekkür ederiz.",
        },
      ],
    },
  ],
  keyword_gaps: [
    {
      keyword: "profesyonel kurumsal çözümler",
      competitor_frequency: 14,
      target_frequency: 0,
      priority: "URGENT",
      recommendation: "Web sitenizde hizmet çeşitlerinizi detaylandıran özel bir alt sayfa oluşturun.",
    },
    {
      keyword: "istanbul kurumsal fiyat teklifi",
      competitor_frequency: 10,
      target_frequency: 0,
      priority: "URGENT",
      recommendation: "Bölgesel aramalarda öne çıkmak için fiyat teklifi ve süreç adımlarını anlatan içerik ekleyin.",
    },
    {
      keyword: "hızlı teslimat ve kalite garantisi",
      competitor_frequency: 8,
      target_frequency: 0,
      priority: "HIGH",
      recommendation: "Müşteri güvenini artırmak için kalite sertifikalarınızı ve süreç güvencelerinizi öne çıkarın.",
    },
  ],
  keyword_rankings: [
    {
      keyword: "kurumsal hizmetler",
      rank_position: 18,
      page_number: 2,
      search_volume: "1.900/ay",
      difficulty: "Orta",
      status: "Sıralamada",
      url_path: "/hizmetler",
    },
    {
      keyword: "en iyi kurumsal çözümler",
      rank_position: 24,
      page_number: 3,
      search_volume: "850/ay",
      difficulty: "Zor",
      status: "Fırsat",
      url_path: "/",
    },
    {
      keyword: "hızlı kurumsal fiyat teklifi",
      rank_position: 65,
      page_number: 7,
      search_volume: "520/ay",
      difficulty: "Kolay",
      status: "Eksik İçerik",
      url_path: "/teklif-al",
    },
  ],
  missing_keywords_guide: {
    industry: "Kurumsal Hizmetler",
    recommended_keywords: [
      {
        keyword: "kurumsal hizmetler istanbul",
        monthly_searches: "2.400",
        importance: "Yüksek",
        target_placement: "Title & H1 Başlık",
      },
      {
        keyword: "profesyonel kurumsal fiyat teklifi",
        monthly_searches: "1.200",
        importance: "Kritik",
        target_placement: "Meta Description & H2",
      },
      {
        keyword: "güvenilir kurumsal çözümler",
        monthly_searches: "890",
        importance: "Orta",
        target_placement: "Gövde Metni & SSS",
      },
    ],
    implementation_tips: {
      title_example: "Kurumsal Hizmetler İstanbul | Profesyonel Çözümler & Hızlı Teklif",
      h1_example: "İstanbul Kurumsal Hizmet ve Profesyonel İş Çözümleri",
      meta_example: "İstanbul genelinde kaliteli, şeffaf ve profesyonel kurumsal çözümler. Aynı gün hızlı fiyat teklifi almak ve uzman ekibimizle tanışmak için hemen tıklayın.",
      content_guide: "Ana sayfanıza ve hizmet sayfalarınıza en az 600 kelimelik özgün açıklama, süreç adımları ve müşteri güven referansları ekleyin.",
    },
  },
  actions: [
    {
      id: "act-1",
      category: "Local-GBP",
      title: "Google Haritalar Profilinde Yorum Toplama Süreci Başlatın",
      problem:
        "Harita lideri rakip 156 yoruma (4.9 ⭐) sahipken firmanız ornekfirma.com profilinde yalnızca 12 yorum bulunuyor. Google Haritalar Local 3-Pack kutusunda görünürlüğünüzü artırmak için yorum hacmi gereklidir.",
      solution_guide:
        "1. Google İşletme Profilinizden 'Yorum iste' kısa bağlantısını kopyalayın.\n2. Hizmet teslimatı tamamlanan müşterilerinize WhatsApp veya e-posta ile bu bağlantıyı iletin.\n3. Hedef: İlk 30 günde en az +15 gerçek müşteri yorumu toplayarak harita algoritmasında aktifleşmek.",
      impact: "HIGH",
      effort: "EASY",
      priority: "URGENT",
      is_completed: false,
      suggested_fix:
        "Sayın müşterimiz, bizimle çalıştığınız için teşekkür ederiz. Hizmet deneyiminizi değerlendirmek için 30 saniyenizi ayırıp Google Haritalar profilimize puan verir misiniz? [GOOGLE_MAPS_LINK]",
      competitor_benchmark: {
        target: 12,
        leader: 156,
        gap: -144,
      },
    },
    {
      id: "act-2",
      category: "Technical",
      title: "LocalBusiness ve Organization Schema.org Kod Bloğunu Ekleyin",
      problem:
        "İlk 3 rakibin tamamında Schema.org zengin sonuç etiketleri mevcutken sitenizin kaynak kodunda yapılandırılmış veri tespit edilemedi.",
      solution_guide:
        "Aşağıdaki hazır üretilmiş JSON-LD kodunu web sitenizin <head> ... </head> etiketleri arasına yerleştirin ve Google Zengin Sonuçlar Testi ile doğrulayın.",
      impact: "HIGH",
      effort: "EASY",
      priority: "URGENT",
      is_completed: false,
      suggested_fix: `<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "LocalBusiness",
  "name": "Örnek İşletme",
  "url": "https://ornekfirma.com",
  "telephone": "+90 212 555 0100",
  "priceRange": "$$",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "Merkez Mah. İş Kuleleri Kat:4",
    "addressLocality": "Şişli",
    "addressRegion": "İstanbul",
    "addressCountry": "TR"
  }
}
</script>`,
      competitor_benchmark: {
        target_has_schema: false,
        competitors_with_schema: 3,
      },
    },
    {
      id: "act-3",
      category: "Content-Gap",
      title: "Sayfa İçerik Hacmini Artırın ve Hizmet Detayları Ekleyin",
      problem:
        "Rakipler ortalama 1.390 kelimelik zengin içerik barındırırken sitenizde 520 kelime bulunuyor (-870 kelime açığı).",
      solution_guide:
        "1. Hizmet süreçleri, standartlar ve sık sorulan sorular hakkında en az 600 kelimelik özgün teknik metin ekleyin.\n2. Sayfa altına 4 soruluk Sıkça Sorulan Sorular (SSS) bloğu yerleştirin.",
      impact: "HIGH",
      effort: "MODERATE",
      priority: "HIGH",
      is_completed: false,
      suggested_fix: `Önerilen H2 Başlıkları:
- H2: Hizmetlerimiz ve Çalışma Prensiplerimiz
- H2: Kalite Standartları ve Güvence
- H2: İstanbul Bölgesinde Hızlı Teklif ve Danışmanlık
- H2: Sıkça Sorulan Sorular (SSS)`,
      competitor_benchmark: {
        target_words: 520,
        competitor_avg_words: 1390,
        gap: -870,
      },
    },
    {
      id: "act-4",
      category: "On-Page",
      title: "Title ve Meta Description Etiketlerini CTR Odaklı Optimize Edin",
      problem:
        "Mevcut başlığınız arama sonuçlarında rakipler kadar tıklama çekmiyor ve anahtar kelimeyi ilk 30 karakterde taşımıyor.",
      solution_guide:
        "Aşağıdaki hazır optimize edilmiş Title ve Meta Description etiketlerini sitenizin ilgili sayfasına yerleştirin.",
      impact: "MEDIUM",
      effort: "EASY",
      priority: "HIGH",
      is_completed: true,
      suggested_fix: `<title>Kurumsal Hizmetler | Hızlı Teklif & Kalite Garantisi - Örnek İşletme</title>
<meta name="description" content="İstanbul bölgesinde profesyonel kurumsal çözümler ve danışmanlık hizmetleri. Şeffaf fiyatlandırma ve hızlı destek için hemen teklif alın.">`,
    },
    {
      id: "act-5",
      category: "Technical",
      title: "Mobil Sayfa Hızını (LCP) Optimize Edin ve Görselleri Sıkıştırın",
      problem:
        "Mobil hız skorunuz 42/100. İlk 3 rakibin ortalaması 78/100 (36 puan daha yavaşsınız). Yavaş sayfalar mobil sıralamaları doğrudan olumsuz etkiler.",
      solution_guide:
        "1. Görselleri modern WebP/AVIF formatına dönüştürüp sıkıştırın.\n2. CSS ve JS dosyalarını erteleyin (defer).\n3. Sunucu yanıt süresini (TTFB) 600ms altına indirin.",
      impact: "HIGH",
      effort: "HARD",
      priority: "MEDIUM",
      is_completed: false,
      suggested_fix: "Optimizasyon: Sitedeki büyük resimleri WebP sıkıştırmasıyla %70 küçültün ve lazy load uygulayın.",
      competitor_benchmark: {
        target_score: 42,
        competitor_avg_score: 78,
        gap: -36,
      },
    },
  ],
  maps_audit: {
    score: 58,
    pin_registered: true,
    pin_status_label: "Pin Servisi Aktif (Doğrulama Rozeti Eksik)",
    is_verified: false,
    total_checks: 8,
    passed_checks: 3,
    failed_checks: 3,
    checks: [
      {
        id: "chk-1",
        category: "PIN_LOCATION",
        title: "Google Harita Pin Servisi Kaydı (Google Harita İğnesi)",
        status: "pass",
        status_label: "Pin Servisi Aktif & İğne Konumu Kayıtlı",
        description: "İşletmenizin Google Haritalar üzerinde aktif pin servisi kaydı bulundu. İğne konumu haritada işaretlenmiş.",
        action_needed: "Pin konumunun kapı numarası ve giriş kapısıyla tam milimetrik örtüştüğünü düzenli kontrol edin.",
        impact: "Çok Yüksek",
      },
      {
        id: "chk-2",
        category: "CATEGORIES",
        title: "Kategori & İkincil Faaliyet Alanları",
        status: "warning",
        status_label: "Eksik: 3 İkincil Sektör Kategorisi Tanımlanmalı",
        description: "Sadece tek ana kategori seçilmiş. Google Harita algoritması 9 adede kadar ikincil alt kategoriye izin verir.",
        action_needed: "Google İşletme profilinize 3 adet ikincil faaliyet kategorisi ekleyin.",
        impact: "Çok Yüksek",
      },
      {
        id: "chk-3",
        category: "HOURS",
        title: "Haftalık Çalışma Saatleri & Resmi Tatil Planlaması",
        status: "warning",
        status_label: "Eksik: Çalışma Saatleri Eksik veya Güncel Değil",
        description: "Google Haritalar çalışma saatleri boş olan işletmeleri arama sonuçlarında alt sıralara öteler.",
        action_needed: "Haftalık mesai saatlerinizi ve resmi tatil günleri açık/kapalı durumunuzu kaydedin.",
        impact: "Yüksek",
      },
      {
        id: "chk-4",
        category: "PHOTOS",
        title: "Google Harita Vitrin & Fotoğraf Galerisi (En Az 15 Fotoğraf)",
        status: "fail",
        status_label: "Kritik Açık: Haritada Yetersiz Görsel",
        description: "15+ yüksek çözünürlüklü fotoğraf bulunan işletmeler %42 daha fazla yol tarifi alır.",
        action_needed: "Dış tabela, ofis/atölye içi, ekip ve tamamlanan işlerinize ait en az 15 adet HD fotoğraf yükleyin.",
        impact: "Yüksek",
      },
      {
        id: "chk-5",
        category: "CONTACT",
        title: "Müşteri Yorum Hacmi & Sosyal Kanıt",
        status: "warning",
        status_label: "Kritik Açık: 12 Yorum (Rakiplerin Gerisinde)",
        description: "Rakipler ortalama 90+ yoruma sahipken 12 yorumla ilk 3 sırada tutunamazsınız.",
        action_needed: "WhatsApp yorum şablonunu müşterilerinize göndererek yeni 5 yıldızlı yorumlar toplayın.",
        impact: "Çok Yüksek",
      },
      {
        id: "chk-6",
        category: "CONTACT",
        title: "İşletme Sahibi Yorum Yanıtlama Oranı",
        status: "warning",
        status_label: "Geliştirilmeli: Yorum Yanıtlama Oranı %100 Olmalı",
        description: "Gelen her yoruma 24 saat içinde yanıt vermek harita sıralamasını doğrudan güçlendirir.",
        action_needed: "Mevcut ve yeni tüm müşteri yorumlarına kurumsal işletme yanıtları ekleyin.",
        impact: "Orta",
      },
      {
        id: "chk-7",
        category: "PRODUCTS",
        title: "Google Harita Ürünler & Fiyat Menüsü Kataloğu",
        status: "fail",
        status_label: "Eksik: Ürün Kataloğu Tanımlanmamış",
        description: "Kullanıcılar haritada hizmetlerinizin fotoğraflı ürün vitrinini görmek ister.",
        action_needed: "En çok satılan 4-6 ana hizmetinizi fotoğraflarıyla Harita Ürünler sekmesine ekleyin.",
        impact: "Yüksek",
      },
      {
        id: "chk-8",
        category: "CONTACT",
        title: "Doğrudan WhatsApp & Teklif Butonu Bağlantısı",
        status: "pass",
        status_label: "WhatsApp Entegrasyonu Aktif",
        description: "Google Harita profilinde doğrudan WhatsApp butonu dönüşüm oranını 3 kat artırır.",
        action_needed: "WhatsApp bağlantısını güncel tutun.",
        impact: "Yüksek",
      },
    ],
    pin_service_guide: [
      {
        step: 1,
        title: "Google Harita Pin Servisi Kaydını Başlatın",
        description: "business.google.com adresine tarayıcınızdan giriş yapın. Google hesabınızla oturum açıp işletme adınızı yazın. Çıkan sonuçta yoksa 'İşletmenizi Google'a Ekleyin' seçeneğine tıklayın.",
      },
      {
        step: 2,
        title: "Harita İğnesini (Pin) Milimetrik Sabitleyin",
        description: "Adresinizi yazdıktan sonra harita ekranında kırmızı harita iğnesini dükkanınızın veya bina ana giriş kapısının tam üzerine sürükleyip bırakın.",
      },
      {
        step: 3,
        title: "Doğrulama Rozetini (Google Onayı) Tamamlayın",
        description: "Google genellikle kısa bir video doğrulaması veya SMS kodu ister. Bu adımı tamamlayarak 'Doğrulanmış İşletme Rozeti' kazanın.",
      },
      {
        step: 4,
        title: "Çalışma Saatlerini ve En Az 15 Fotoğraf Yükleyin",
        description: "Haftalık açılış-kapanış saatlerini, telefon numaranızı, web sitenizi ve en az 15 yüksek kaliteli fotoğrafınızı yükleyin.",
      },
      {
        step: 5,
        title: "WhatsApp Yorum Şablonu ile İlk Yorumları Toplayın",
        description: "Google panelinizden 'Yorum İsteyin' bağlantısını kopyalayıp sistemimizdeki WhatsApp şablonu ile müşterilerinize gönderin.",
      },
    ],
  },
};
